[package]
name = "bouyomi4rs"
description = "BouyomiClientは、棒読みちゃんのアプリ連携機能（TCP）を使用して、テキストを音声で読み上げるためのRustライブラリです。"
version = "0.2.1"
homepage = "https://github.com/go-numb/bouyomi4rs"
edition = "2021"
authors = ["_numbp"]
license = "MIT"